run:
  deadline: 1m
  tests: false
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"
    - ".*\\.gen\\.go$"
    - "_test\\.go$"
    - "testing.go$"
    - ".*doc\\.go$"

linters-settings:
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  misspell:
    locale: US
  gci:
    sections:
      - standard
      - default
      - prefix(berty.tech)
      # - prefix(github.com/libp2p)
      # - prefix(github.com/ipfs)

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    #- exhaustive    # nice to have
    - exportloopref
    - gci
    - gochecknoinits
    #- gocognit      # nice to have
    #- goconst
    - gocritic
    #- godot         # nice to have
    #- goerr113      # nice to have
    - gofmt
    - gofumpt
    - goimports
    - revive
    #- gomnd         # nice to have
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    #- nolintlint
    - exportloopref
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - unused
