// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: replicationtypes/bertyreplication.proto

package replicationtypes

import (
	protocoltypes "berty.tech/weshnet/v2/pkg/protocoltypes"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicatedGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey            string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty" gorm:"primaryKey"`
	SignPub              string `protobuf:"bytes,2,opt,name=sign_pub,json=signPub,proto3" json:"sign_pub,omitempty"`
	LinkKey              string `protobuf:"bytes,3,opt,name=link_key,json=linkKey,proto3" json:"link_key,omitempty"`
	CreatedAt            int64  `protobuf:"varint,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64  `protobuf:"varint,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MetadataEntriesCount int64  `protobuf:"varint,102,opt,name=metadata_entries_count,json=metadataEntriesCount,proto3" json:"metadata_entries_count,omitempty"`
	MetadataLatestHead   string `protobuf:"bytes,103,opt,name=metadata_latest_head,json=metadataLatestHead,proto3" json:"metadata_latest_head,omitempty"`
	MessageEntriesCount  int64  `protobuf:"varint,104,opt,name=message_entries_count,json=messageEntriesCount,proto3" json:"message_entries_count,omitempty"`
	MessageLatestHead    string `protobuf:"bytes,105,opt,name=message_latest_head,json=messageLatestHead,proto3" json:"message_latest_head,omitempty"`
}

func (x *ReplicatedGroup) Reset() {
	*x = ReplicatedGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicatedGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicatedGroup) ProtoMessage() {}

func (x *ReplicatedGroup) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicatedGroup.ProtoReflect.Descriptor instead.
func (*ReplicatedGroup) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicatedGroup) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ReplicatedGroup) GetSignPub() string {
	if x != nil {
		return x.SignPub
	}
	return ""
}

func (x *ReplicatedGroup) GetLinkKey() string {
	if x != nil {
		return x.LinkKey
	}
	return ""
}

func (x *ReplicatedGroup) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ReplicatedGroup) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ReplicatedGroup) GetMetadataEntriesCount() int64 {
	if x != nil {
		return x.MetadataEntriesCount
	}
	return 0
}

func (x *ReplicatedGroup) GetMetadataLatestHead() string {
	if x != nil {
		return x.MetadataLatestHead
	}
	return ""
}

func (x *ReplicatedGroup) GetMessageEntriesCount() int64 {
	if x != nil {
		return x.MessageEntriesCount
	}
	return 0
}

func (x *ReplicatedGroup) GetMessageLatestHead() string {
	if x != nil {
		return x.MessageLatestHead
	}
	return ""
}

type ReplicatedGroupToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicatedGroupPublicKey string           `protobuf:"bytes,1,opt,name=replicated_group_public_key,json=replicatedGroupPublicKey,proto3" json:"replicated_group_public_key,omitempty" gorm:"index;primaryKey;autoIncrement:false"`
	ReplicatedGroup          *ReplicatedGroup `protobuf:"bytes,2,opt,name=replicated_group,json=replicatedGroup,proto3" json:"replicated_group,omitempty"`
	TokenIssuer              string           `protobuf:"bytes,3,opt,name=token_issuer,json=tokenIssuer,proto3" json:"token_issuer,omitempty" gorm:"primaryKey;autoIncrement:false"`
	TokenId                  string           `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty" gorm:"primaryKey;autoIncrement:false"`
	CreatedAt                int64            `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ReplicatedGroupToken) Reset() {
	*x = ReplicatedGroupToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicatedGroupToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicatedGroupToken) ProtoMessage() {}

func (x *ReplicatedGroupToken) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicatedGroupToken.ProtoReflect.Descriptor instead.
func (*ReplicatedGroupToken) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicatedGroupToken) GetReplicatedGroupPublicKey() string {
	if x != nil {
		return x.ReplicatedGroupPublicKey
	}
	return ""
}

func (x *ReplicatedGroupToken) GetReplicatedGroup() *ReplicatedGroup {
	if x != nil {
		return x.ReplicatedGroup
	}
	return nil
}

func (x *ReplicatedGroupToken) GetTokenIssuer() string {
	if x != nil {
		return x.TokenIssuer
	}
	return ""
}

func (x *ReplicatedGroupToken) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ReplicatedGroupToken) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ReplicationServiceReplicateGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplicationServiceReplicateGroup) Reset() {
	*x = ReplicationServiceReplicateGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationServiceReplicateGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceReplicateGroup) ProtoMessage() {}

func (x *ReplicationServiceReplicateGroup) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceReplicateGroup.ProtoReflect.Descriptor instead.
func (*ReplicationServiceReplicateGroup) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{2}
}

type ReplicateGlobalStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplicateGlobalStats) Reset() {
	*x = ReplicateGlobalStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicateGlobalStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateGlobalStats) ProtoMessage() {}

func (x *ReplicateGlobalStats) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateGlobalStats.ProtoReflect.Descriptor instead.
func (*ReplicateGlobalStats) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{3}
}

type ReplicateGroupStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplicateGroupStats) Reset() {
	*x = ReplicateGroupStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicateGroupStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateGroupStats) ProtoMessage() {}

func (x *ReplicateGroupStats) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateGroupStats.ProtoReflect.Descriptor instead.
func (*ReplicateGroupStats) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{4}
}

type ReplicationServiceReplicateGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group *protocoltypes.Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *ReplicationServiceReplicateGroup_Request) Reset() {
	*x = ReplicationServiceReplicateGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationServiceReplicateGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceReplicateGroup_Request) ProtoMessage() {}

func (x *ReplicationServiceReplicateGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceReplicateGroup_Request.ProtoReflect.Descriptor instead.
func (*ReplicationServiceReplicateGroup_Request) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ReplicationServiceReplicateGroup_Request) GetGroup() *protocoltypes.Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type ReplicationServiceReplicateGroup_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ReplicationServiceReplicateGroup_Reply) Reset() {
	*x = ReplicationServiceReplicateGroup_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationServiceReplicateGroup_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceReplicateGroup_Reply) ProtoMessage() {}

func (x *ReplicationServiceReplicateGroup_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceReplicateGroup_Reply.ProtoReflect.Descriptor instead.
func (*ReplicationServiceReplicateGroup_Reply) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ReplicationServiceReplicateGroup_Reply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReplicateGlobalStats_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReplicateGlobalStats_Request) Reset() {
	*x = ReplicateGlobalStats_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicateGlobalStats_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateGlobalStats_Request) ProtoMessage() {}

func (x *ReplicateGlobalStats_Request) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateGlobalStats_Request.ProtoReflect.Descriptor instead.
func (*ReplicateGlobalStats_Request) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{3, 0}
}

type ReplicateGlobalStats_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartedAt            int64 `protobuf:"varint,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ReplicatedGroups     int64 `protobuf:"varint,2,opt,name=replicated_groups,json=replicatedGroups,proto3" json:"replicated_groups,omitempty"`
	TotalMetadataEntries int64 `protobuf:"varint,3,opt,name=total_metadata_entries,json=totalMetadataEntries,proto3" json:"total_metadata_entries,omitempty"`
	TotalMessageEntries  int64 `protobuf:"varint,4,opt,name=total_message_entries,json=totalMessageEntries,proto3" json:"total_message_entries,omitempty"`
}

func (x *ReplicateGlobalStats_Reply) Reset() {
	*x = ReplicateGlobalStats_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicateGlobalStats_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateGlobalStats_Reply) ProtoMessage() {}

func (x *ReplicateGlobalStats_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateGlobalStats_Reply.ProtoReflect.Descriptor instead.
func (*ReplicateGlobalStats_Reply) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ReplicateGlobalStats_Reply) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ReplicateGlobalStats_Reply) GetReplicatedGroups() int64 {
	if x != nil {
		return x.ReplicatedGroups
	}
	return 0
}

func (x *ReplicateGlobalStats_Reply) GetTotalMetadataEntries() int64 {
	if x != nil {
		return x.TotalMetadataEntries
	}
	return 0
}

func (x *ReplicateGlobalStats_Reply) GetTotalMessageEntries() int64 {
	if x != nil {
		return x.TotalMessageEntries
	}
	return 0
}

type ReplicateGroupStats_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupPublicKey string `protobuf:"bytes,1,opt,name=group_public_key,json=groupPublicKey,proto3" json:"group_public_key,omitempty"`
}

func (x *ReplicateGroupStats_Request) Reset() {
	*x = ReplicateGroupStats_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicateGroupStats_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateGroupStats_Request) ProtoMessage() {}

func (x *ReplicateGroupStats_Request) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateGroupStats_Request.ProtoReflect.Descriptor instead.
func (*ReplicateGroupStats_Request) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ReplicateGroupStats_Request) GetGroupPublicKey() string {
	if x != nil {
		return x.GroupPublicKey
	}
	return ""
}

type ReplicateGroupStats_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group *ReplicatedGroup `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *ReplicateGroupStats_Reply) Reset() {
	*x = ReplicateGroupStats_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationtypes_bertyreplication_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicateGroupStats_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateGroupStats_Reply) ProtoMessage() {}

func (x *ReplicateGroupStats_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_replicationtypes_bertyreplication_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateGroupStats_Reply.ProtoReflect.Descriptor instead.
func (*ReplicateGroupStats_Reply) Descriptor() ([]byte, []int) {
	return file_replicationtypes_bertyreplication_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ReplicateGroupStats_Reply) GetGroup() *ReplicatedGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

var File_replicationtypes_bertyreplication_proto protoreflect.FileDescriptor

var file_replicationtypes_bertyreplication_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x62, 0x65, 0x72, 0x74, 0x79, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x77, 0x65, 0x73, 0x68, 0x6e,
	0x65, 0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x74, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x74,
	0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x03, 0x0a, 0x0f,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x35, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x16, 0x9a, 0x84, 0x9e, 0x03, 0x11, 0x67, 0x6f, 0x72, 0x6d, 0x3a, 0x22,
	0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x22, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x70,
	0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x75,
	0x62, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x64, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x65, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x34, 0x0a, 0x16, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x66, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x30, 0x0a, 0x14, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x18, 0x67, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x68, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x18, 0x69, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x22, 0x90, 0x03, 0x0a, 0x14, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x6f, 0x0a, 0x1b, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x30, 0x9a, 0x84, 0x9e, 0x03, 0x2b, 0x67, 0x6f, 0x72, 0x6d, 0x3a,
	0x22, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x3b, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65,
	0x79, 0x3b, 0x61, 0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x3a,
	0x66, 0x61, 0x6c, 0x73, 0x65, 0x22, 0x52, 0x18, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x52, 0x0a, 0x10, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x77, 0x65, 0x73,
	0x68, 0x6e, 0x65, 0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x0f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x4d, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2a, 0x9a, 0x84, 0x9e, 0x03,
	0x25, 0x67, 0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65,
	0x79, 0x3b, 0x61, 0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x3a,
	0x66, 0x61, 0x6c, 0x73, 0x65, 0x22, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2a, 0x9a, 0x84, 0x9e, 0x03, 0x25, 0x67, 0x6f, 0x72, 0x6d,
	0x3a, 0x22, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x3b, 0x61, 0x75, 0x74,
	0x6f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x3a, 0x66, 0x61, 0x6c, 0x73, 0x65,
	0x22, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x78, 0x0a, 0x20, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x3b, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x65, 0x73, 0x68, 0x6e, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x17, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x22, 0xe1, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x09, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xbd, 0x01, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x34, 0x0a,
	0x16, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x73, 0x1a,
	0x33, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x1a, 0x46, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3d, 0x0a,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x77,
	0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x32, 0xab, 0x03, 0x0a,
	0x12, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x92, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x40, 0x2e, 0x77, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74,
	0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3e, 0x2e, 0x77, 0x65, 0x73, 0x68, 0x6e,
	0x65, 0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x80, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x34, 0x2e, 0x77, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x77, 0x65, 0x73, 0x68, 0x6e, 0x65,
	0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x7d, 0x0a, 0x13, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x33, 0x2e, 0x77, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74, 0x2e, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x77, 0x65, 0x73, 0x68, 0x6e, 0x65,
	0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2c, 0x5a, 0x2a, 0x62, 0x65,
	0x72, 0x74, 0x79, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x77, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x74,
	0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_replicationtypes_bertyreplication_proto_rawDescOnce sync.Once
	file_replicationtypes_bertyreplication_proto_rawDescData = file_replicationtypes_bertyreplication_proto_rawDesc
)

func file_replicationtypes_bertyreplication_proto_rawDescGZIP() []byte {
	file_replicationtypes_bertyreplication_proto_rawDescOnce.Do(func() {
		file_replicationtypes_bertyreplication_proto_rawDescData = protoimpl.X.CompressGZIP(file_replicationtypes_bertyreplication_proto_rawDescData)
	})
	return file_replicationtypes_bertyreplication_proto_rawDescData
}

var file_replicationtypes_bertyreplication_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_replicationtypes_bertyreplication_proto_goTypes = []any{
	(*ReplicatedGroup)(nil),                          // 0: weshnet.replication.v1.ReplicatedGroup
	(*ReplicatedGroupToken)(nil),                     // 1: weshnet.replication.v1.ReplicatedGroupToken
	(*ReplicationServiceReplicateGroup)(nil),         // 2: weshnet.replication.v1.ReplicationServiceReplicateGroup
	(*ReplicateGlobalStats)(nil),                     // 3: weshnet.replication.v1.ReplicateGlobalStats
	(*ReplicateGroupStats)(nil),                      // 4: weshnet.replication.v1.ReplicateGroupStats
	(*ReplicationServiceReplicateGroup_Request)(nil), // 5: weshnet.replication.v1.ReplicationServiceReplicateGroup.Request
	(*ReplicationServiceReplicateGroup_Reply)(nil),   // 6: weshnet.replication.v1.ReplicationServiceReplicateGroup.Reply
	(*ReplicateGlobalStats_Request)(nil),             // 7: weshnet.replication.v1.ReplicateGlobalStats.Request
	(*ReplicateGlobalStats_Reply)(nil),               // 8: weshnet.replication.v1.ReplicateGlobalStats.Reply
	(*ReplicateGroupStats_Request)(nil),              // 9: weshnet.replication.v1.ReplicateGroupStats.Request
	(*ReplicateGroupStats_Reply)(nil),                // 10: weshnet.replication.v1.ReplicateGroupStats.Reply
	(*protocoltypes.Group)(nil),                      // 11: weshnet.protocol.v1.Group
}
var file_replicationtypes_bertyreplication_proto_depIdxs = []int32{
	0,  // 0: weshnet.replication.v1.ReplicatedGroupToken.replicated_group:type_name -> weshnet.replication.v1.ReplicatedGroup
	11, // 1: weshnet.replication.v1.ReplicationServiceReplicateGroup.Request.group:type_name -> weshnet.protocol.v1.Group
	0,  // 2: weshnet.replication.v1.ReplicateGroupStats.Reply.group:type_name -> weshnet.replication.v1.ReplicatedGroup
	5,  // 3: weshnet.replication.v1.ReplicationService.ReplicateGroup:input_type -> weshnet.replication.v1.ReplicationServiceReplicateGroup.Request
	7,  // 4: weshnet.replication.v1.ReplicationService.ReplicateGlobalStats:input_type -> weshnet.replication.v1.ReplicateGlobalStats.Request
	9,  // 5: weshnet.replication.v1.ReplicationService.ReplicateGroupStats:input_type -> weshnet.replication.v1.ReplicateGroupStats.Request
	6,  // 6: weshnet.replication.v1.ReplicationService.ReplicateGroup:output_type -> weshnet.replication.v1.ReplicationServiceReplicateGroup.Reply
	8,  // 7: weshnet.replication.v1.ReplicationService.ReplicateGlobalStats:output_type -> weshnet.replication.v1.ReplicateGlobalStats.Reply
	10, // 8: weshnet.replication.v1.ReplicationService.ReplicateGroupStats:output_type -> weshnet.replication.v1.ReplicateGroupStats.Reply
	6,  // [6:9] is the sub-list for method output_type
	3,  // [3:6] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_replicationtypes_bertyreplication_proto_init() }
func file_replicationtypes_bertyreplication_proto_init() {
	if File_replicationtypes_bertyreplication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_replicationtypes_bertyreplication_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicatedGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicatedGroupToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicationServiceReplicateGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicateGlobalStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicateGroupStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicationServiceReplicateGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicationServiceReplicateGroup_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicateGlobalStats_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicateGlobalStats_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicateGroupStats_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replicationtypes_bertyreplication_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ReplicateGroupStats_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_replicationtypes_bertyreplication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replicationtypes_bertyreplication_proto_goTypes,
		DependencyIndexes: file_replicationtypes_bertyreplication_proto_depIdxs,
		MessageInfos:      file_replicationtypes_bertyreplication_proto_msgTypes,
	}.Build()
	File_replicationtypes_bertyreplication_proto = out.File
	file_replicationtypes_bertyreplication_proto_rawDesc = nil
	file_replicationtypes_bertyreplication_proto_goTypes = nil
	file_replicationtypes_bertyreplication_proto_depIdxs = nil
}
