# yamllint disable-line rule:document-start
name: "Question"
description: Ask a question about this project.
labels: ["question"]
body:
  - type: checkboxes
    attributes:
      label: Asking a question, not reporting a bug
      description: >-
        If your question is "Why did I get this error?" and you think it is a
        bug, then please open a Bug Report at
        https://github.com/berty/weshnet/issues/new/
      options:
        - label: This question is not about a bug
          required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search to see if an issue already exists for your question.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: >-
        Provide your question with enough detail that it is helpful to anyone
        reading the question (maybe years later).
      placeholder: How do I ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: >-
        Is it a general question about the design and goals of weshnet, or
        about how to use it in an app (or some other context)?
      placeholder: This is a question about ...
    validations:
      required: true
