// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: errcode/errcode.proto

package errcode

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ErrCode int32

const (
	Undefined                                  ErrCode = 0
	TODO                                       ErrCode = 666
	ErrNotImplemented                          ErrCode = 777
	ErrInternal                                ErrCode = 888
	ErrInvalidInput                            ErrCode = 100
	ErrInvalidRange                            ErrCode = 101
	ErrMissingInput                            ErrCode = 102
	ErrSerialization                           ErrCode = 103
	ErrDeserialization                         ErrCode = 104
	ErrStreamRead                              ErrCode = 105
	ErrStreamWrite                             ErrCode = 106
	ErrStreamTransform                         ErrCode = 110
	ErrStreamSendAndClose                      ErrCode = 111
	ErrStreamHeaderWrite                       ErrCode = 112
	ErrStreamHeaderRead                        ErrCode = 115
	ErrStreamSink                              ErrCode = 113
	ErrStreamCloseAndRecv                      ErrCode = 114
	ErrMissingMapKey                           ErrCode = 107
	ErrDBWrite                                 ErrCode = 108
	ErrDBRead                                  ErrCode = 109
	ErrDBDestroy                               ErrCode = 120
	ErrDBMigrate                               ErrCode = 121
	ErrDBReplay                                ErrCode = 122
	ErrDBRestore                               ErrCode = 123
	ErrDBOpen                                  ErrCode = 124
	ErrDBClose                                 ErrCode = 125
	ErrCryptoRandomGeneration                  ErrCode = 200
	ErrCryptoKeyGeneration                     ErrCode = 201
	ErrCryptoNonceGeneration                   ErrCode = 202
	ErrCryptoSignature                         ErrCode = 203
	ErrCryptoSignatureVerification             ErrCode = 204
	ErrCryptoDecrypt                           ErrCode = 205
	ErrCryptoDecryptPayload                    ErrCode = 206
	ErrCryptoEncrypt                           ErrCode = 207
	ErrCryptoKeyConversion                     ErrCode = 208
	ErrCryptoCipherInit                        ErrCode = 209
	ErrCryptoKeyDerivation                     ErrCode = 210
	ErrMap                                     ErrCode = 300
	ErrForEach                                 ErrCode = 301
	ErrKeystoreGet                             ErrCode = 400
	ErrKeystorePut                             ErrCode = 401
	ErrNotFound                                ErrCode = 404
	ErrOrbitDBInit                             ErrCode = 1000
	ErrOrbitDBOpen                             ErrCode = 1001
	ErrOrbitDBAppend                           ErrCode = 1002
	ErrOrbitDBDeserialization                  ErrCode = 1003
	ErrOrbitDBStoreCast                        ErrCode = 1004
	ErrIPFSAdd                                 ErrCode = 1050
	ErrIPFSGet                                 ErrCode = 1051
	ErrIPFSInit                                ErrCode = 1052
	ErrIPFSSetupConfig                         ErrCode = 1053
	ErrIPFSSetupRepo                           ErrCode = 1054
	ErrIPFSSetupHost                           ErrCode = 1055
	ErrHandshakeOwnEphemeralKeyGenSend         ErrCode = 1100
	ErrHandshakePeerEphemeralKeyRecv           ErrCode = 1101
	ErrHandshakeRequesterAuthenticateBoxKeyGen ErrCode = 1102
	ErrHandshakeResponderAcceptBoxKeyGen       ErrCode = 1103
	ErrHandshakeRequesterHello                 ErrCode = 1104
	ErrHandshakeResponderHello                 ErrCode = 1105
	ErrHandshakeRequesterAuthenticate          ErrCode = 1106
	ErrHandshakeResponderAccept                ErrCode = 1107
	ErrHandshakeRequesterAcknowledge           ErrCode = 1108
	ErrContactRequestSameAccount               ErrCode = 1200
	ErrContactRequestContactAlreadyAdded       ErrCode = 1201
	ErrContactRequestContactBlocked            ErrCode = 1202
	ErrContactRequestContactUndefined          ErrCode = 1203
	ErrContactRequestIncomingAlreadyReceived   ErrCode = 1204
	ErrGroupMemberLogEventOpen                 ErrCode = 1300
	ErrGroupMemberLogEventSignature            ErrCode = 1301
	ErrGroupMemberUnknownGroupID               ErrCode = 1302
	ErrGroupSecretOtherDestMember              ErrCode = 1303
	ErrGroupSecretAlreadySentToMember          ErrCode = 1304
	ErrGroupInvalidType                        ErrCode = 1305
	ErrGroupMissing                            ErrCode = 1306
	ErrGroupActivate                           ErrCode = 1307
	ErrGroupDeactivate                         ErrCode = 1308
	ErrGroupInfo                               ErrCode = 1309
	ErrGroupUnknown                            ErrCode = 1310
	// Event errors
	ErrEventListMetadata                   ErrCode = 1400
	ErrEventListMessage                    ErrCode = 1401
	ErrMessageKeyPersistencePut            ErrCode = 1500
	ErrMessageKeyPersistenceGet            ErrCode = 1501
	ErrBridgeInterrupted                   ErrCode = 1600
	ErrBridgeNotRunning                    ErrCode = 1601
	ErrMessengerInvalidDeepLink            ErrCode = 2000
	ErrMessengerDeepLinkRequiresPassphrase ErrCode = 2001
	ErrMessengerDeepLinkInvalidPassphrase  ErrCode = 2002
	ErrMessengerStreamEvent                ErrCode = 2003
	ErrMessengerContactMetadataUnmarshal   ErrCode = 2004
	ErrDBEntryAlreadyExists                ErrCode = 2100
	ErrDBAddConversation                   ErrCode = 2101
	ErrDBAddContactRequestOutgoingSent     ErrCode = 2102
	ErrDBAddContactRequestOutgoingEnqueud  ErrCode = 2103
	ErrDBAddContactRequestIncomingReceived ErrCode = 2104
	ErrDBAddContactRequestIncomingAccepted ErrCode = 2105
	ErrDBAddGroupMemberDeviceAdded         ErrCode = 2106
	ErrDBMultipleRecords                   ErrCode = 2107
	ErrReplayProcessGroupMetadata          ErrCode = 2200
	ErrReplayProcessGroupMessage           ErrCode = 2201
	ErrAttachmentPrepare                   ErrCode = 2300
	ErrAttachmentRetrieve                  ErrCode = 2301
	ErrProtocolSend                        ErrCode = 2302
	ErrProtocolEventUnmarshal              ErrCode = 2303
	ErrProtocolGetGroupInfo                ErrCode = 2304
	// Test Error
	ErrTestEcho                                          ErrCode = 2401
	ErrTestEchoRecv                                      ErrCode = 2402
	ErrTestEchoSend                                      ErrCode = 2403
	ErrCLINoTermcaps                                     ErrCode = 3001
	ErrServicesAuth                                      ErrCode = 4000
	ErrServicesAuthNotInitialized                        ErrCode = 4001
	ErrServicesAuthWrongState                            ErrCode = 4002
	ErrServicesAuthInvalidResponse                       ErrCode = 4003
	ErrServicesAuthServer                                ErrCode = 4004
	ErrServicesAuthCodeChallenge                         ErrCode = 4005
	ErrServicesAuthServiceInvalidToken                   ErrCode = 4006
	ErrServicesAuthServiceNotSupported                   ErrCode = 4007
	ErrServicesAuthUnknownToken                          ErrCode = 4008
	ErrServicesAuthInvalidURL                            ErrCode = 4009
	ErrServiceReplication                                ErrCode = 4100
	ErrServiceReplicationServer                          ErrCode = 4101
	ErrServiceReplicationMissingEndpoint                 ErrCode = 4102
	ErrServicesDirectory                                 ErrCode = 4200
	ErrServicesDirectoryInvalidVerifiedCredentialSubject ErrCode = 4201
	ErrServicesDirectoryExistingRecordNotFound           ErrCode = 4202
	ErrServicesDirectoryRecordLockedAndCantBeReplaced    ErrCode = 4203
	ErrServicesDirectoryExplicitReplaceFlagRequired      ErrCode = 4204
	ErrServicesDirectoryInvalidVerifiedCredential        ErrCode = 4205
	ErrServicesDirectoryExpiredVerifiedCredential        ErrCode = 4206
	ErrServicesDirectoryInvalidVerifiedCredentialID      ErrCode = 4207
	ErrBertyAccount                                      ErrCode = 5000
	ErrBertyAccountNoIDSpecified                         ErrCode = 5001
	ErrBertyAccountAlreadyOpened                         ErrCode = 5002
	ErrBertyAccountInvalidIDFormat                       ErrCode = 5003
	ErrBertyAccountLoggerDecorator                       ErrCode = 5004
	ErrBertyAccountGRPCClient                            ErrCode = 5005
	ErrBertyAccountOpenAccount                           ErrCode = 5006
	ErrBertyAccountDataNotFound                          ErrCode = 5007
	ErrBertyAccountMetadataUpdate                        ErrCode = 5008
	ErrBertyAccountManagerOpen                           ErrCode = 5009
	ErrBertyAccountManagerClose                          ErrCode = 5010
	ErrBertyAccountInvalidCLIArgs                        ErrCode = 5011
	ErrBertyAccountFSError                               ErrCode = 5012
	ErrBertyAccountAlreadyExists                         ErrCode = 5013
	ErrBertyAccountNoBackupSpecified                     ErrCode = 5014
	ErrBertyAccountIDGenFailed                           ErrCode = 5015
	ErrBertyAccountCreationFailed                        ErrCode = 5016
	ErrBertyAccountUpdateFailed                          ErrCode = 5017
	ErrAppStorageNotSupported                            ErrCode = 5018
	ErrPush                                              ErrCode = 6000
	ErrPushWrongAccount                                  ErrCode = 6001
	ErrPushUnableToDecrypt                               ErrCode = 6002
	ErrPushInvalidPayload                                ErrCode = 6003
	ErrPushInvalidServerConfig                           ErrCode = 6004
	ErrPushMissingBundleID                               ErrCode = 6005
	ErrPushUnknownDestination                            ErrCode = 6006
	ErrPushProvider                                      ErrCode = 6007
	ErrPushUnknownProvider                               ErrCode = 6008
	ErrNoProvidersConfigured                             ErrCode = 6009
	ErrInvalidPrivateKey                                 ErrCode = 6010
)

var ErrCode_name = map[int32]string{
	0:    "Undefined",
	666:  "TODO",
	777:  "ErrNotImplemented",
	888:  "ErrInternal",
	100:  "ErrInvalidInput",
	101:  "ErrInvalidRange",
	102:  "ErrMissingInput",
	103:  "ErrSerialization",
	104:  "ErrDeserialization",
	105:  "ErrStreamRead",
	106:  "ErrStreamWrite",
	110:  "ErrStreamTransform",
	111:  "ErrStreamSendAndClose",
	112:  "ErrStreamHeaderWrite",
	115:  "ErrStreamHeaderRead",
	113:  "ErrStreamSink",
	114:  "ErrStreamCloseAndRecv",
	107:  "ErrMissingMapKey",
	108:  "ErrDBWrite",
	109:  "ErrDBRead",
	120:  "ErrDBDestroy",
	121:  "ErrDBMigrate",
	122:  "ErrDBReplay",
	123:  "ErrDBRestore",
	124:  "ErrDBOpen",
	125:  "ErrDBClose",
	200:  "ErrCryptoRandomGeneration",
	201:  "ErrCryptoKeyGeneration",
	202:  "ErrCryptoNonceGeneration",
	203:  "ErrCryptoSignature",
	204:  "ErrCryptoSignatureVerification",
	205:  "ErrCryptoDecrypt",
	206:  "ErrCryptoDecryptPayload",
	207:  "ErrCryptoEncrypt",
	208:  "ErrCryptoKeyConversion",
	209:  "ErrCryptoCipherInit",
	210:  "ErrCryptoKeyDerivation",
	300:  "ErrMap",
	301:  "ErrForEach",
	400:  "ErrKeystoreGet",
	401:  "ErrKeystorePut",
	404:  "ErrNotFound",
	1000: "ErrOrbitDBInit",
	1001: "ErrOrbitDBOpen",
	1002: "ErrOrbitDBAppend",
	1003: "ErrOrbitDBDeserialization",
	1004: "ErrOrbitDBStoreCast",
	1050: "ErrIPFSAdd",
	1051: "ErrIPFSGet",
	1052: "ErrIPFSInit",
	1053: "ErrIPFSSetupConfig",
	1054: "ErrIPFSSetupRepo",
	1055: "ErrIPFSSetupHost",
	1100: "ErrHandshakeOwnEphemeralKeyGenSend",
	1101: "ErrHandshakePeerEphemeralKeyRecv",
	1102: "ErrHandshakeRequesterAuthenticateBoxKeyGen",
	1103: "ErrHandshakeResponderAcceptBoxKeyGen",
	1104: "ErrHandshakeRequesterHello",
	1105: "ErrHandshakeResponderHello",
	1106: "ErrHandshakeRequesterAuthenticate",
	1107: "ErrHandshakeResponderAccept",
	1108: "ErrHandshakeRequesterAcknowledge",
	1200: "ErrContactRequestSameAccount",
	1201: "ErrContactRequestContactAlreadyAdded",
	1202: "ErrContactRequestContactBlocked",
	1203: "ErrContactRequestContactUndefined",
	1204: "ErrContactRequestIncomingAlreadyReceived",
	1300: "ErrGroupMemberLogEventOpen",
	1301: "ErrGroupMemberLogEventSignature",
	1302: "ErrGroupMemberUnknownGroupID",
	1303: "ErrGroupSecretOtherDestMember",
	1304: "ErrGroupSecretAlreadySentToMember",
	1305: "ErrGroupInvalidType",
	1306: "ErrGroupMissing",
	1307: "ErrGroupActivate",
	1308: "ErrGroupDeactivate",
	1309: "ErrGroupInfo",
	1310: "ErrGroupUnknown",
	1400: "ErrEventListMetadata",
	1401: "ErrEventListMessage",
	1500: "ErrMessageKeyPersistencePut",
	1501: "ErrMessageKeyPersistenceGet",
	1600: "ErrBridgeInterrupted",
	1601: "ErrBridgeNotRunning",
	2000: "ErrMessengerInvalidDeepLink",
	2001: "ErrMessengerDeepLinkRequiresPassphrase",
	2002: "ErrMessengerDeepLinkInvalidPassphrase",
	2003: "ErrMessengerStreamEvent",
	2004: "ErrMessengerContactMetadataUnmarshal",
	2100: "ErrDBEntryAlreadyExists",
	2101: "ErrDBAddConversation",
	2102: "ErrDBAddContactRequestOutgoingSent",
	2103: "ErrDBAddContactRequestOutgoingEnqueud",
	2104: "ErrDBAddContactRequestIncomingReceived",
	2105: "ErrDBAddContactRequestIncomingAccepted",
	2106: "ErrDBAddGroupMemberDeviceAdded",
	2107: "ErrDBMultipleRecords",
	2200: "ErrReplayProcessGroupMetadata",
	2201: "ErrReplayProcessGroupMessage",
	2300: "ErrAttachmentPrepare",
	2301: "ErrAttachmentRetrieve",
	2302: "ErrProtocolSend",
	2303: "ErrProtocolEventUnmarshal",
	2304: "ErrProtocolGetGroupInfo",
	2401: "ErrTestEcho",
	2402: "ErrTestEchoRecv",
	2403: "ErrTestEchoSend",
	3001: "ErrCLINoTermcaps",
	4000: "ErrServicesAuth",
	4001: "ErrServicesAuthNotInitialized",
	4002: "ErrServicesAuthWrongState",
	4003: "ErrServicesAuthInvalidResponse",
	4004: "ErrServicesAuthServer",
	4005: "ErrServicesAuthCodeChallenge",
	4006: "ErrServicesAuthServiceInvalidToken",
	4007: "ErrServicesAuthServiceNotSupported",
	4008: "ErrServicesAuthUnknownToken",
	4009: "ErrServicesAuthInvalidURL",
	4100: "ErrServiceReplication",
	4101: "ErrServiceReplicationServer",
	4102: "ErrServiceReplicationMissingEndpoint",
	4200: "ErrServicesDirectory",
	4201: "ErrServicesDirectoryInvalidVerifiedCredentialSubject",
	4202: "ErrServicesDirectoryExistingRecordNotFound",
	4203: "ErrServicesDirectoryRecordLockedAndCantBeReplaced",
	4204: "ErrServicesDirectoryExplicitReplaceFlagRequired",
	4205: "ErrServicesDirectoryInvalidVerifiedCredential",
	4206: "ErrServicesDirectoryExpiredVerifiedCredential",
	4207: "ErrServicesDirectoryInvalidVerifiedCredentialID",
	5000: "ErrBertyAccount",
	5001: "ErrBertyAccountNoIDSpecified",
	5002: "ErrBertyAccountAlreadyOpened",
	5003: "ErrBertyAccountInvalidIDFormat",
	5004: "ErrBertyAccountLoggerDecorator",
	5005: "ErrBertyAccountGRPCClient",
	5006: "ErrBertyAccountOpenAccount",
	5007: "ErrBertyAccountDataNotFound",
	5008: "ErrBertyAccountMetadataUpdate",
	5009: "ErrBertyAccountManagerOpen",
	5010: "ErrBertyAccountManagerClose",
	5011: "ErrBertyAccountInvalidCLIArgs",
	5012: "ErrBertyAccountFSError",
	5013: "ErrBertyAccountAlreadyExists",
	5014: "ErrBertyAccountNoBackupSpecified",
	5015: "ErrBertyAccountIDGenFailed",
	5016: "ErrBertyAccountCreationFailed",
	5017: "ErrBertyAccountUpdateFailed",
	5018: "ErrAppStorageNotSupported",
	6000: "ErrPush",
	6001: "ErrPushWrongAccount",
	6002: "ErrPushUnableToDecrypt",
	6003: "ErrPushInvalidPayload",
	6004: "ErrPushInvalidServerConfig",
	6005: "ErrPushMissingBundleID",
	6006: "ErrPushUnknownDestination",
	6007: "ErrPushProvider",
	6008: "ErrPushUnknownProvider",
	6009: "ErrNoProvidersConfigured",
	6010: "ErrInvalidPrivateKey",
}

var ErrCode_value = map[string]int32{
	"Undefined":                          0,
	"TODO":                               666,
	"ErrNotImplemented":                  777,
	"ErrInternal":                        888,
	"ErrInvalidInput":                    100,
	"ErrInvalidRange":                    101,
	"ErrMissingInput":                    102,
	"ErrSerialization":                   103,
	"ErrDeserialization":                 104,
	"ErrStreamRead":                      105,
	"ErrStreamWrite":                     106,
	"ErrStreamTransform":                 110,
	"ErrStreamSendAndClose":              111,
	"ErrStreamHeaderWrite":               112,
	"ErrStreamHeaderRead":                115,
	"ErrStreamSink":                      113,
	"ErrStreamCloseAndRecv":              114,
	"ErrMissingMapKey":                   107,
	"ErrDBWrite":                         108,
	"ErrDBRead":                          109,
	"ErrDBDestroy":                       120,
	"ErrDBMigrate":                       121,
	"ErrDBReplay":                        122,
	"ErrDBRestore":                       123,
	"ErrDBOpen":                          124,
	"ErrDBClose":                         125,
	"ErrCryptoRandomGeneration":          200,
	"ErrCryptoKeyGeneration":             201,
	"ErrCryptoNonceGeneration":           202,
	"ErrCryptoSignature":                 203,
	"ErrCryptoSignatureVerification":     204,
	"ErrCryptoDecrypt":                   205,
	"ErrCryptoDecryptPayload":            206,
	"ErrCryptoEncrypt":                   207,
	"ErrCryptoKeyConversion":             208,
	"ErrCryptoCipherInit":                209,
	"ErrCryptoKeyDerivation":             210,
	"ErrMap":                             300,
	"ErrForEach":                         301,
	"ErrKeystoreGet":                     400,
	"ErrKeystorePut":                     401,
	"ErrNotFound":                        404,
	"ErrOrbitDBInit":                     1000,
	"ErrOrbitDBOpen":                     1001,
	"ErrOrbitDBAppend":                   1002,
	"ErrOrbitDBDeserialization":          1003,
	"ErrOrbitDBStoreCast":                1004,
	"ErrIPFSAdd":                         1050,
	"ErrIPFSGet":                         1051,
	"ErrIPFSInit":                        1052,
	"ErrIPFSSetupConfig":                 1053,
	"ErrIPFSSetupRepo":                   1054,
	"ErrIPFSSetupHost":                   1055,
	"ErrHandshakeOwnEphemeralKeyGenSend": 1100,
	"ErrHandshakePeerEphemeralKeyRecv":   1101,
	"ErrHandshakeRequesterAuthenticateBoxKeyGen":           1102,
	"ErrHandshakeResponderAcceptBoxKeyGen":                 1103,
	"ErrHandshakeRequesterHello":                           1104,
	"ErrHandshakeResponderHello":                           1105,
	"ErrHandshakeRequesterAuthenticate":                    1106,
	"ErrHandshakeResponderAccept":                          1107,
	"ErrHandshakeRequesterAcknowledge":                     1108,
	"ErrContactRequestSameAccount":                         1200,
	"ErrContactRequestContactAlreadyAdded":                 1201,
	"ErrContactRequestContactBlocked":                      1202,
	"ErrContactRequestContactUndefined":                    1203,
	"ErrContactRequestIncomingAlreadyReceived":             1204,
	"ErrGroupMemberLogEventOpen":                           1300,
	"ErrGroupMemberLogEventSignature":                      1301,
	"ErrGroupMemberUnknownGroupID":                         1302,
	"ErrGroupSecretOtherDestMember":                        1303,
	"ErrGroupSecretAlreadySentToMember":                    1304,
	"ErrGroupInvalidType":                                  1305,
	"ErrGroupMissing":                                      1306,
	"ErrGroupActivate":                                     1307,
	"ErrGroupDeactivate":                                   1308,
	"ErrGroupInfo":                                         1309,
	"ErrGroupUnknown":                                      1310,
	"ErrEventListMetadata":                                 1400,
	"ErrEventListMessage":                                  1401,
	"ErrMessageKeyPersistencePut":                          1500,
	"ErrMessageKeyPersistenceGet":                          1501,
	"ErrBridgeInterrupted":                                 1600,
	"ErrBridgeNotRunning":                                  1601,
	"ErrMessengerInvalidDeepLink":                          2000,
	"ErrMessengerDeepLinkRequiresPassphrase":               2001,
	"ErrMessengerDeepLinkInvalidPassphrase":                2002,
	"ErrMessengerStreamEvent":                              2003,
	"ErrMessengerContactMetadataUnmarshal":                 2004,
	"ErrDBEntryAlreadyExists":                              2100,
	"ErrDBAddConversation":                                 2101,
	"ErrDBAddContactRequestOutgoingSent":                   2102,
	"ErrDBAddContactRequestOutgoingEnqueud":                2103,
	"ErrDBAddContactRequestIncomingReceived":               2104,
	"ErrDBAddContactRequestIncomingAccepted":               2105,
	"ErrDBAddGroupMemberDeviceAdded":                       2106,
	"ErrDBMultipleRecords":                                 2107,
	"ErrReplayProcessGroupMetadata":                        2200,
	"ErrReplayProcessGroupMessage":                         2201,
	"ErrAttachmentPrepare":                                 2300,
	"ErrAttachmentRetrieve":                                2301,
	"ErrProtocolSend":                                      2302,
	"ErrProtocolEventUnmarshal":                            2303,
	"ErrProtocolGetGroupInfo":                              2304,
	"ErrTestEcho":                                          2401,
	"ErrTestEchoRecv":                                      2402,
	"ErrTestEchoSend":                                      2403,
	"ErrCLINoTermcaps":                                     3001,
	"ErrServicesAuth":                                      4000,
	"ErrServicesAuthNotInitialized":                        4001,
	"ErrServicesAuthWrongState":                            4002,
	"ErrServicesAuthInvalidResponse":                       4003,
	"ErrServicesAuthServer":                                4004,
	"ErrServicesAuthCodeChallenge":                         4005,
	"ErrServicesAuthServiceInvalidToken":                   4006,
	"ErrServicesAuthServiceNotSupported":                   4007,
	"ErrServicesAuthUnknownToken":                          4008,
	"ErrServicesAuthInvalidURL":                            4009,
	"ErrServiceReplication":                                4100,
	"ErrServiceReplicationServer":                          4101,
	"ErrServiceReplicationMissingEndpoint":                 4102,
	"ErrServicesDirectory":                                 4200,
	"ErrServicesDirectoryInvalidVerifiedCredentialSubject": 4201,
	"ErrServicesDirectoryExistingRecordNotFound":           4202,
	"ErrServicesDirectoryRecordLockedAndCantBeReplaced":    4203,
	"ErrServicesDirectoryExplicitReplaceFlagRequired":      4204,
	"ErrServicesDirectoryInvalidVerifiedCredential":        4205,
	"ErrServicesDirectoryExpiredVerifiedCredential":        4206,
	"ErrServicesDirectoryInvalidVerifiedCredentialID":      4207,
	"ErrBertyAccount":                                      5000,
	"ErrBertyAccountNoIDSpecified":                         5001,
	"ErrBertyAccountAlreadyOpened":                         5002,
	"ErrBertyAccountInvalidIDFormat":                       5003,
	"ErrBertyAccountLoggerDecorator":                       5004,
	"ErrBertyAccountGRPCClient":                            5005,
	"ErrBertyAccountOpenAccount":                           5006,
	"ErrBertyAccountDataNotFound":                          5007,
	"ErrBertyAccountMetadataUpdate":                        5008,
	"ErrBertyAccountManagerOpen":                           5009,
	"ErrBertyAccountManagerClose":                          5010,
	"ErrBertyAccountInvalidCLIArgs":                        5011,
	"ErrBertyAccountFSError":                               5012,
	"ErrBertyAccountAlreadyExists":                         5013,
	"ErrBertyAccountNoBackupSpecified":                     5014,
	"ErrBertyAccountIDGenFailed":                           5015,
	"ErrBertyAccountCreationFailed":                        5016,
	"ErrBertyAccountUpdateFailed":                          5017,
	"ErrAppStorageNotSupported":                            5018,
	"ErrPush":                                              6000,
	"ErrPushWrongAccount":                                  6001,
	"ErrPushUnableToDecrypt":                               6002,
	"ErrPushInvalidPayload":                                6003,
	"ErrPushInvalidServerConfig":                           6004,
	"ErrPushMissingBundleID":                               6005,
	"ErrPushUnknownDestination":                            6006,
	"ErrPushProvider":                                      6007,
	"ErrPushUnknownProvider":                               6008,
	"ErrNoProvidersConfigured":                             6009,
	"ErrInvalidPrivateKey":                                 6010,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fb5abb189af31c1a, []int{0}
}

type ErrDetails struct {
	Codes                []ErrCode `protobuf:"varint,1,rep,packed,name=codes,proto3,enum=weshnet.errcode.ErrCode" json:"codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ErrDetails) Reset()         { *m = ErrDetails{} }
func (m *ErrDetails) String() string { return proto.CompactTextString(m) }
func (*ErrDetails) ProtoMessage()    {}
func (*ErrDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb5abb189af31c1a, []int{0}
}
func (m *ErrDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErrDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErrDetails.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErrDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrDetails.Merge(m, src)
}
func (m *ErrDetails) XXX_Size() int {
	return m.Size()
}
func (m *ErrDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ErrDetails proto.InternalMessageInfo

func (m *ErrDetails) GetCodes() []ErrCode {
	if m != nil {
		return m.Codes
	}
	return nil
}

func init() {
	proto.RegisterEnum("weshnet.errcode.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterType((*ErrDetails)(nil), "weshnet.errcode.ErrDetails")
}

func init() { proto.RegisterFile("errcode/errcode.proto", fileDescriptor_fb5abb189af31c1a) }

var fileDescriptor_fb5abb189af31c1a = []byte{
	// 2177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0x59, 0x70, 0x5c, 0x47,
	0xd5, 0xce, 0x24, 0x7f, 0xac, 0x51, 0xdb, 0x89, 0x8e, 0x3a, 0x4e, 0xbc, 0x24, 0x91, 0x26, 0xfe,
	0xe3, 0x28, 0x98, 0xca, 0x08, 0x42, 0x8a, 0x2a, 0xaa, 0x78, 0x99, 0x4d, 0xf2, 0x94, 0xb5, 0x4c,
	0xcd, 0xc8, 0xa4, 0x8a, 0xb7, 0xd6, 0xbd, 0x47, 0x33, 0x37, 0xba, 0xd3, 0x7d, 0xdd, 0xb7, 0x47,
	0xf6, 0x04, 0xa8, 0xe2, 0x01, 0x28, 0xc2, 0x9a, 0x80, 0x93, 0xd8, 0xce, 0xc2, 0xbe, 0x55, 0x41,
	0x15, 0x4b, 0x58, 0x02, 0x2f, 0xe1, 0x2d, 0x40, 0x16, 0xdb, 0xc9, 0x23, 0x54, 0x11, 0xf3, 0x92,
	0x8d, 0x7d, 0x73, 0x28, 0xb6, 0xea, 0xbe, 0xe7, 0x8e, 0xee, 0x48, 0x63, 0x03, 0x4f, 0xd2, 0x9c,
	0xf3, 0xf5, 0xe9, 0xb3, 0x9f, 0xd3, 0x97, 0x5d, 0x8f, 0x5a, 0x7b, 0xca, 0xc7, 0x59, 0xfa, 0x5b,
	0x8c, 0xb4, 0x32, 0x8a, 0x4f, 0x1c, 0xc7, 0xb8, 0x23, 0xd1, 0x14, 0x89, 0xbc, 0x7f, 0x77, 0x5b,
	0xb5, 0x95, 0xe3, 0xcd, 0xda, 0xff, 0x12, 0xd8, 0x81, 0x77, 0x32, 0x56, 0xd3, 0xba, 0x8a, 0x46,
	0x04, 0x61, 0xcc, 0x8b, 0xec, 0x6a, 0x8b, 0x8d, 0xf7, 0xe6, 0x0a, 0x57, 0xdd, 0x7e, 0xed, 0x9d,
	0x7b, 0x8b, 0x5b, 0x84, 0x14, 0x6b, 0x5a, 0x57, 0x94, 0x8f, 0xcd, 0x04, 0x76, 0xe8, 0xa9, 0x83,
	0x6c, 0x8c, 0x48, 0xfc, 0x1a, 0x36, 0x7e, 0x54, 0xfa, 0xb8, 0x16, 0x48, 0xf4, 0xe1, 0x0a, 0x3e,
	0xce, 0xfe, 0x6f, 0x65, 0xb9, 0xba, 0x0c, 0x67, 0xae, 0xe6, 0x37, 0xb0, 0xc9, 0x9a, 0xd6, 0x4b,
	0xca, 0xd4, 0xbb, 0x51, 0x88, 0x5d, 0x94, 0x06, 0x7d, 0xb8, 0x6f, 0x07, 0x07, 0xb6, 0xb3, 0xa6,
	0x75, 0x5d, 0x1a, 0xd4, 0x52, 0x84, 0x70, 0x71, 0x07, 0xbf, 0x8e, 0x4d, 0x38, 0xca, 0x86, 0x08,
	0x03, 0xbf, 0x2e, 0xa3, 0x9e, 0x01, 0x7f, 0x98, 0xd8, 0x14, 0xb2, 0x8d, 0x80, 0x44, 0x5c, 0x0c,
	0xe2, 0x38, 0x90, 0xed, 0x04, 0xb9, 0xc6, 0x77, 0x33, 0xa8, 0x69, 0xdd, 0x42, 0x1d, 0x88, 0x30,
	0xb8, 0x57, 0x98, 0x40, 0x49, 0x68, 0xf3, 0x1b, 0x18, 0x77, 0x26, 0xc6, 0x43, 0xf4, 0x0e, 0x9f,
	0x64, 0xd7, 0x58, 0xb4, 0xd1, 0x28, 0xba, 0x4d, 0x14, 0x3e, 0x04, 0x9c, 0xb3, 0x6b, 0x07, 0xa4,
	0xbb, 0x75, 0x60, 0x10, 0xee, 0xa1, 0xe3, 0x09, 0x6d, 0x45, 0x0b, 0x19, 0xaf, 0x29, 0xdd, 0x05,
	0xc9, 0xf7, 0xb1, 0xeb, 0x07, 0xf4, 0x16, 0x4a, 0xbf, 0x24, 0xfd, 0x4a, 0xa8, 0x62, 0x04, 0xc5,
	0xf7, 0xb2, 0xdd, 0x03, 0xd6, 0x61, 0x14, 0x3e, 0xea, 0x44, 0x58, 0xc4, 0xf7, 0xb0, 0xeb, 0xb6,
	0x70, 0xdc, 0xcd, 0xf1, 0x90, 0x32, 0xad, 0x40, 0xae, 0xc3, 0xb1, 0xa1, 0x0b, 0x9c, 0xe4, 0x92,
	0xf4, 0x9b, 0xe8, 0x6d, 0x80, 0x26, 0x43, 0xc9, 0xfa, 0x45, 0x11, 0x1d, 0xc1, 0x3e, 0xac, 0xf3,
	0x6b, 0x93, 0x58, 0x96, 0x93, 0xcb, 0x42, 0x1b, 0x11, 0xf7, 0xdb, 0x5d, 0xd1, 0xe5, 0xc0, 0x76,
	0xb9, 0x9f, 0x55, 0x8c, 0x8d, 0x56, 0x7d, 0x38, 0x31, 0xa0, 0x2c, 0x06, 0x6d, 0x2d, 0x0c, 0x42,
	0x9f, 0x4f, 0xb8, 0x90, 0xd8, 0x23, 0x51, 0x28, 0xfa, 0x70, 0xef, 0x00, 0xd2, 0xc4, 0xd8, 0x28,
	0x8d, 0xf0, 0x9e, 0x81, 0xd4, 0xe5, 0x08, 0x25, 0xbc, 0x77, 0x70, 0x69, 0x62, 0xfb, 0xfb, 0xf8,
	0x14, 0xdb, 0x67, 0x33, 0x42, 0xf7, 0x23, 0xa3, 0x9a, 0x42, 0xfa, 0xaa, 0x3b, 0x8f, 0x12, 0x75,
	0xe2, 0xf4, 0xa7, 0x73, 0xfc, 0x46, 0x76, 0xc3, 0x80, 0x7f, 0x04, 0xfb, 0x19, 0xe6, 0x4f, 0x72,
	0xfc, 0x66, 0xb6, 0x77, 0xc0, 0x5c, 0x52, 0xd2, 0xc3, 0x0c, 0xfb, 0xa7, 0x39, 0xbe, 0xc7, 0x85,
	0x22, 0x61, 0xb7, 0x82, 0xb6, 0x14, 0xa6, 0xa7, 0x11, 0x7e, 0x96, 0xe3, 0xff, 0xcf, 0xa6, 0xb6,
	0x33, 0xde, 0x85, 0x3a, 0x58, 0x0b, 0xbc, 0xe4, 0xf4, 0x33, 0x39, 0x7e, 0xbd, 0x73, 0x5a, 0x02,
	0xaa, 0xa2, 0x67, 0xff, 0xc2, 0xb3, 0x39, 0x7e, 0x13, 0xdb, 0xb3, 0x95, 0xdc, 0x10, 0xfd, 0x50,
	0x09, 0x1f, 0x9e, 0x1b, 0x3e, 0x54, 0x93, 0xc9, 0xa1, 0xe7, 0xb7, 0x59, 0x51, 0x51, 0x72, 0x03,
	0x75, 0x6c, 0x2f, 0x3a, 0x9b, 0xe3, 0x7b, 0x5d, 0x90, 0x13, 0x66, 0x25, 0x88, 0x3a, 0xa8, 0xeb,
	0x32, 0x30, 0x70, 0x6e, 0xdb, 0xb1, 0x2a, 0xea, 0x60, 0x23, 0xd1, 0xef, 0x7c, 0x8e, 0xef, 0x64,
	0x3b, 0x6c, 0x50, 0x45, 0x04, 0x5f, 0xbf, 0x92, 0x4f, 0x38, 0xb7, 0xce, 0x29, 0x5d, 0x13, 0x5e,
	0x07, 0xbe, 0x71, 0x25, 0xbf, 0xce, 0xa5, 0xe6, 0x11, 0xec, 0xbb, 0x38, 0xcc, 0xa3, 0x81, 0xfb,
	0xaf, 0xda, 0x42, 0x6c, 0xf4, 0x0c, 0x3c, 0x70, 0x15, 0x95, 0xd5, 0x92, 0x32, 0x73, 0xaa, 0x27,
	0x7d, 0x38, 0x99, 0xc2, 0x96, 0xf5, 0x6a, 0x60, 0xaa, 0x65, 0xa7, 0xcb, 0xcb, 0x63, 0xc3, 0x44,
	0x17, 0xcc, 0x57, 0xc6, 0xc8, 0x5c, 0x22, 0x96, 0xa2, 0x08, 0xa5, 0x0f, 0xaf, 0x8e, 0x51, 0x50,
	0x89, 0xbc, 0xb5, 0x92, 0x5e, 0x1b, 0x23, 0x8b, 0x89, 0xdf, 0xb2, 0xba, 0x54, 0x44, 0x6c, 0xe0,
	0xf5, 0x31, 0xb2, 0xa3, 0xde, 0x98, 0x6b, 0x95, 0x7c, 0x1f, 0xce, 0xe4, 0x33, 0x04, 0x6b, 0xc3,
	0x23, 0xf9, 0xb4, 0x0b, 0x34, 0xe6, 0x5a, 0x4e, 0xb3, 0x47, 0xf3, 0x14, 0x66, 0x4b, 0x69, 0xa1,
	0xe9, 0x45, 0x15, 0x25, 0xd7, 0x82, 0x36, 0x3c, 0x96, 0x27, 0xed, 0x06, 0x8c, 0x26, 0x46, 0x0a,
	0x1e, 0xdf, 0x46, 0x3e, 0xac, 0x62, 0x03, 0x9f, 0xc9, 0xf3, 0x19, 0x76, 0xa0, 0xa6, 0xf5, 0x61,
	0x21, 0xfd, 0xb8, 0x23, 0xd6, 0x71, 0xf9, 0xb8, 0xac, 0x45, 0x1d, 0xec, 0xa2, 0x16, 0x61, 0x92,
	0x78, 0xb6, 0x6a, 0xe1, 0x99, 0x3c, 0x3f, 0xc8, 0x0a, 0x59, 0x60, 0x03, 0x51, 0x67, 0x91, 0xae,
	0xe6, 0x9e, 0xcd, 0xf3, 0x59, 0x76, 0x28, 0x0b, 0x6b, 0xe2, 0xb1, 0x1e, 0xc6, 0x06, 0x75, 0xa9,
	0x67, 0x3a, 0x28, 0x8d, 0xcd, 0x34, 0x2c, 0xab, 0x13, 0x89, 0x6c, 0x78, 0x2e, 0xcf, 0xdf, 0xc4,
	0x6e, 0x1d, 0x3e, 0x10, 0x47, 0x4a, 0xfa, 0xa8, 0x4b, 0x9e, 0x87, 0x91, 0xd9, 0x84, 0x3e, 0x9f,
	0xe7, 0xd3, 0x6c, 0xff, 0x48, 0xd9, 0x87, 0x31, 0x0c, 0x15, 0x9c, 0x1d, 0x01, 0x20, 0x59, 0x09,
	0xe0, 0x5c, 0x9e, 0xdf, 0xc6, 0x6e, 0xf9, 0x8f, 0xda, 0xc1, 0xf9, 0x3c, 0x2f, 0xb0, 0x1b, 0x2f,
	0xa3, 0x14, 0xbc, 0xb0, 0xcd, 0x1d, 0x9b, 0x92, 0xbc, 0x75, 0xa9, 0x8e, 0x87, 0xe8, 0xb7, 0x11,
	0x5e, 0xcc, 0xf3, 0x5b, 0xd8, 0x4d, 0xae, 0xf5, 0x4b, 0x23, 0x3c, 0x43, 0xa0, 0x96, 0xe8, 0x62,
	0xc9, 0xf3, 0x54, 0x4f, 0x1a, 0xf8, 0xe6, 0x38, 0x39, 0x60, 0x18, 0x42, 0xbf, 0x4a, 0xa1, 0x46,
	0xe1, 0xf7, 0x4b, 0xbe, 0x8f, 0x3e, 0x7c, 0x6b, 0x9c, 0xdf, 0xca, 0xa6, 0x2f, 0x05, 0x2d, 0x87,
	0xca, 0x5b, 0x47, 0x1f, 0xbe, 0x3d, 0x4e, 0x46, 0x8e, 0x44, 0x6d, 0xce, 0x9e, 0xef, 0x8c, 0xf3,
	0x3b, 0xd8, 0xed, 0xdb, 0x70, 0x75, 0xe9, 0xa9, 0x6e, 0x20, 0xdb, 0x74, 0x73, 0x13, 0x3d, 0x0c,
	0x36, 0xd0, 0x87, 0x27, 0xc6, 0xc9, 0xb9, 0xf3, 0x5a, 0xf5, 0xa2, 0x45, 0xec, 0xae, 0xa2, 0x5e,
	0x50, 0xed, 0xda, 0x06, 0x4a, 0xe3, 0xca, 0xe2, 0x24, 0x23, 0xed, 0x46, 0x00, 0x36, 0xbb, 0xd0,
	0x83, 0x8c, 0x3c, 0x92, 0x41, 0x1d, 0x95, 0xd6, 0x63, 0xd2, 0x51, 0xea, 0x55, 0x78, 0x88, 0xf1,
	0x03, 0xec, 0xe6, 0x14, 0xd2, 0x42, 0x4f, 0xa3, 0x59, 0x36, 0x1d, 0xb4, 0xb3, 0xc9, 0x24, 0x27,
	0xe0, 0x61, 0x46, 0x46, 0x66, 0x30, 0xa4, 0x71, 0x0b, 0xa5, 0x59, 0x51, 0x84, 0x3b, 0xc5, 0xa8,
	0xe8, 0x12, 0xe1, 0xc9, 0x70, 0x5c, 0xe9, 0x47, 0x08, 0xa7, 0x19, 0xdf, 0xed, 0x86, 0x63, 0xa2,
	0x48, 0x32, 0x23, 0xe0, 0x0c, 0xa3, 0x32, 0x71, 0xd4, 0x92, 0x67, 0x6c, 0xe3, 0x41, 0x78, 0x84,
	0x51, 0xb5, 0x39, 0x72, 0x15, 0x45, 0xca, 0x78, 0x94, 0xf1, 0x49, 0xd7, 0xfa, 0x49, 0xfe, 0x9a,
	0x82, 0xc7, 0x86, 0x04, 0x93, 0x6d, 0xf0, 0x38, 0xe3, 0xfb, 0xdc, 0xb8, 0x73, 0xfe, 0x58, 0x08,
	0xac, 0x25, 0x46, 0xf8, 0xc2, 0x08, 0xb8, 0x98, 0xea, 0x98, 0x61, 0xc5, 0xb1, 0x68, 0x23, 0xbc,
	0xc1, 0x28, 0x0f, 0x89, 0x70, 0x04, 0xfb, 0x0d, 0xdb, 0x3f, 0x63, 0x83, 0xd2, 0x73, 0x7d, 0xec,
	0xe7, 0x3b, 0x2f, 0x87, 0xb0, 0xad, 0xe3, 0x17, 0x3b, 0xe9, 0xe2, 0xb2, 0x0e, 0xfc, 0x36, 0xba,
	0x35, 0x42, 0xf7, 0x22, 0xbb, 0x5b, 0x3c, 0xb5, 0x8b, 0x2e, 0x4e, 0x58, 0x4b, 0xca, 0x34, 0x7b,
	0x52, 0x5a, 0x37, 0xfc, 0x78, 0x57, 0x46, 0x2c, 0xca, 0x36, 0xa6, 0x7b, 0x45, 0x15, 0x31, 0x5a,
	0xb0, 0x73, 0xf7, 0xec, 0x04, 0x7f, 0x33, 0xbb, 0x2d, 0x8b, 0x48, 0x59, 0x36, 0x8f, 0x02, 0x8d,
	0x71, 0x43, 0xc4, 0x71, 0xd4, 0xd1, 0x22, 0x46, 0x38, 0x37, 0xc1, 0x0f, 0xb1, 0x83, 0xa3, 0xc0,
	0x24, 0x36, 0x83, 0x3d, 0x3f, 0x41, 0xa3, 0x66, 0x80, 0x4d, 0x46, 0xbb, 0x73, 0x0e, 0xbc, 0x30,
	0x41, 0xd5, 0x32, 0xe0, 0x52, 0xf6, 0xa6, 0xde, 0x3c, 0x2a, 0xbb, 0x42, 0xc7, 0x1d, 0x11, 0xc2,
	0x8b, 0xa9, 0xa0, 0x6a, 0xb9, 0x26, 0x8d, 0xee, 0x53, 0x7a, 0xd4, 0x4e, 0x04, 0xb1, 0x89, 0xe1,
	0x09, 0x20, 0xb7, 0x54, 0xcb, 0x25, 0xdf, 0xa7, 0xc1, 0x94, 0x34, 0xea, 0xef, 0x02, 0xf5, 0xc4,
	0x94, 0x95, 0xa9, 0x8e, 0xe5, 0x9e, 0x69, 0xab, 0x40, 0xb6, 0x6d, 0x92, 0xc1, 0xf7, 0x80, 0xcc,
	0xba, 0x0c, 0xb0, 0x26, 0x8f, 0xf5, 0xb0, 0xe7, 0xc3, 0xf7, 0x81, 0xfc, 0x35, 0x02, 0x9b, 0x96,
	0xdc, 0xa0, 0xd6, 0x7e, 0xf0, 0x5f, 0x80, 0x93, 0x46, 0x84, 0x3e, 0x3c, 0x09, 0x34, 0xd7, 0x1d,
	0x38, 0x53, 0x56, 0x55, 0xdc, 0x08, 0x3c, 0x4c, 0x5a, 0xc7, 0x0f, 0x37, 0xcd, 0x5d, 0xec, 0x85,
	0x26, 0x88, 0x42, 0x6c, 0xa2, 0xa7, 0xb4, 0x1f, 0xc3, 0x8f, 0x80, 0xca, 0x2d, 0x59, 0x66, 0x1a,
	0x5a, 0x79, 0x18, 0xc7, 0x24, 0x87, 0x52, 0xf4, 0xd4, 0x24, 0x55, 0xed, 0x28, 0x4c, 0x92, 0xab,
	0xa7, 0x27, 0xe9, 0x86, 0x92, 0x31, 0xc2, 0xeb, 0xd8, 0xf5, 0xb5, 0xa1, 0x31, 0x12, 0x1a, 0xe1,
	0xef, 0x93, 0x7c, 0xbf, 0x5b, 0xd2, 0x36, 0x59, 0x4d, 0x34, 0x3a, 0xc0, 0x0d, 0x84, 0x7f, 0x4c,
	0x52, 0xb5, 0x34, 0xec, 0x9e, 0xed, 0xa9, 0xd0, 0x4d, 0x9b, 0x7f, 0x4e, 0xd2, 0x2c, 0x4d, 0xa9,
	0x2e, 0xfa, 0x9b, 0xb1, 0xfd, 0xd7, 0x24, 0xc5, 0x36, 0xe5, 0xcf, 0xa3, 0xd9, 0xac, 0xc0, 0xf7,
	0x73, 0x9a, 0x96, 0x2b, 0x18, 0x9b, 0x9a, 0xd7, 0x51, 0xf0, 0x12, 0xa7, 0x5b, 0x52, 0x8a, 0x1b,
	0x56, 0x17, 0xb6, 0x52, 0xdd, 0xdd, 0xbf, 0xe2, 0xe9, 0x36, 0xb3, 0x50, 0x5f, 0x52, 0x2b, 0xa8,
	0xbb, 0x9e, 0x88, 0x62, 0x78, 0x72, 0x0f, 0x81, 0x5b, 0xa8, 0xad, 0x5f, 0x63, 0x3b, 0x31, 0xe0,
	0xb3, 0xd3, 0xe4, 0xbc, 0x2c, 0xd5, 0xae, 0xf0, 0x32, 0x30, 0x6e, 0xf6, 0xa3, 0x0f, 0x9f, 0x9b,
	0x26, 0x63, 0xb2, 0x98, 0xbb, 0xb5, 0x92, 0xed, 0x96, 0xb1, 0x3d, 0xe4, 0xf3, 0xd3, 0x14, 0xc0,
	0x2c, 0x3f, 0xdd, 0xe3, 0xdd, 0xdc, 0x89, 0x11, 0xbe, 0x30, 0x4d, 0x3e, 0xcc, 0x82, 0xec, 0xff,
	0xa8, 0xe1, 0x8b, 0xd3, 0x14, 0x9d, 0x2c, 0xcf, 0x3e, 0x36, 0x2a, 0x1d, 0x11, 0x86, 0xb6, 0x4a,
	0xe0, 0x4b, 0xd3, 0x94, 0xd3, 0x5b, 0x8f, 0x07, 0x1e, 0xa6, 0x5d, 0x51, 0xad, 0xa3, 0x84, 0x2f,
	0x5f, 0x06, 0xb8, 0xa4, 0x4c, 0xab, 0x17, 0x45, 0x4a, 0xdb, 0xb4, 0xfb, 0xca, 0x34, 0xb5, 0x88,
	0x2c, 0x90, 0xba, 0x5d, 0x22, 0xea, 0xab, 0xa3, 0xec, 0xa6, 0xcb, 0x8e, 0x36, 0x17, 0xe0, 0x6b,
	0x5b, 0x4c, 0xb2, 0xb9, 0x95, 0xee, 0xa1, 0x1f, 0x28, 0x0c, 0x4b, 0xcf, 0xf0, 0xc8, 0xe8, 0x0f,
	0x16, 0xa8, 0x13, 0x6c, 0x47, 0x50, 0x33, 0xaf, 0x49, 0x3f, 0x52, 0x81, 0x34, 0xf0, 0xa1, 0x02,
	0xa5, 0x66, 0xaa, 0x48, 0x35, 0xd0, 0xe8, 0x19, 0xa5, 0xfb, 0xf0, 0x72, 0x81, 0xbf, 0x83, 0xdd,
	0x35, 0x8a, 0x45, 0x8a, 0x26, 0xdb, 0x31, 0xfa, 0x15, 0x8d, 0xbe, 0xdd, 0x0f, 0x44, 0xd8, 0xea,
	0xad, 0xde, 0x83, 0x9e, 0x81, 0x57, 0x0a, 0xb4, 0xea, 0x6c, 0x3b, 0xea, 0x5a, 0x4c, 0x52, 0xcf,
	0x4a, 0xfb, 0x83, 0x0d, 0xf3, 0xd5, 0x02, 0x7f, 0x3b, 0x7b, 0xeb, 0xa8, 0x03, 0x09, 0x70, 0xc1,
	0xcd, 0x6f, 0xfb, 0x3e, 0x12, 0xd2, 0x94, 0x9d, 0x41, 0xc2, 0x43, 0x1f, 0x5e, 0x2b, 0xf0, 0xbb,
	0xd8, 0xec, 0xe8, 0x8b, 0xac, 0xcd, 0x81, 0x21, 0xe8, 0x5c, 0x28, 0xda, 0xd4, 0x7d, 0x7d, 0x78,
	0xbd, 0xc0, 0xef, 0x64, 0x77, 0xfc, 0x4f, 0x96, 0xc1, 0xaf, 0x2f, 0x79, 0xa6, 0x76, 0x22, 0xb2,
	0x52, 0x47, 0x9c, 0xf9, 0xcd, 0x25, 0xb5, 0xbb, 0xe4, 0x3d, 0xf5, 0x2a, 0xfc, 0xb6, 0x40, 0xd5,
	0x54, 0x46, 0x6d, 0xfa, 0xe9, 0x2e, 0xf4, 0xe1, 0x19, 0x4a, 0xe4, 0x2c, 0x75, 0x49, 0xd5, 0xab,
	0xad, 0x08, 0x3d, 0x27, 0x04, 0xee, 0x1b, 0x05, 0xa1, 0xd6, 0x6e, 0xd7, 0x10, 0xf4, 0xe1, 0x23,
	0x33, 0x54, 0x4f, 0x59, 0x48, 0xfa, 0x58, 0xae, 0xce, 0x29, 0xdd, 0x15, 0x06, 0x3e, 0x3a, 0x0a,
	0xb4, 0xa0, 0xda, 0x6e, 0x36, 0x79, 0x4a, 0x0b, 0xa3, 0x34, 0x7c, 0x6c, 0x86, 0x32, 0x38, 0x0b,
	0x9a, 0x6f, 0x36, 0x2a, 0x95, 0x30, 0xb0, 0x03, 0xe0, 0xe3, 0x33, 0xb4, 0x13, 0x65, 0xf9, 0x56,
	0x8b, 0xd4, 0xa0, 0x4f, 0xcc, 0x50, 0x1a, 0x67, 0x01, 0x55, 0x61, 0xc4, 0x20, 0x29, 0x3e, 0x39,
	0x43, 0x0d, 0x24, 0x8b, 0x18, 0x0c, 0xb3, 0xc8, 0xb7, 0x0d, 0xe2, 0xfe, 0x51, 0xd7, 0x2c, 0x0a,
	0x29, 0xda, 0xa8, 0xdd, 0xea, 0xf5, 0xc0, 0xa8, 0x6b, 0x08, 0x90, 0x3c, 0x38, 0x3f, 0x35, 0xea,
	0x1a, 0xf2, 0x49, 0x65, 0xa1, 0x5e, 0xd2, 0xed, 0x18, 0x3e, 0x3d, 0x43, 0x0f, 0xaf, 0x2c, 0x66,
	0xae, 0x55, 0xd3, 0x5a, 0x69, 0x38, 0x79, 0x19, 0xbf, 0xd3, 0x48, 0x7d, 0x70, 0x86, 0x76, 0xe2,
	0xe1, 0xe8, 0x95, 0x85, 0xb7, 0xde, 0x8b, 0x36, 0x23, 0xf8, 0xd0, 0x28, 0x6b, 0xea, 0xd5, 0x79,
	0x94, 0x73, 0x22, 0x08, 0xd1, 0x87, 0x87, 0x47, 0xe9, 0x5a, 0xd1, 0xe8, 0x6a, 0x9b, 0x30, 0xa7,
	0x46, 0x59, 0x9c, 0xb8, 0x8b, 0x10, 0xa7, 0xd3, 0xd8, 0x95, 0xa2, 0xc8, 0x3e, 0xb5, 0x44, 0x7b,
	0xb8, 0x7f, 0x9d, 0x99, 0xe1, 0xbb, 0xdc, 0x57, 0x99, 0x46, 0x2f, 0xee, 0xc0, 0xef, 0x8a, 0xb4,
	0x0a, 0xd9, 0x5f, 0xae, 0x37, 0xa7, 0x21, 0xfc, 0x7d, 0x91, 0xbc, 0x62, 0x39, 0x47, 0xa5, 0x58,
	0x0d, 0x71, 0x65, 0xf0, 0x2e, 0xfe, 0x43, 0x91, 0x5a, 0x98, 0x65, 0x0e, 0x76, 0x99, 0xe4, 0x55,
	0xfc, 0xc7, 0x22, 0xd9, 0x99, 0xe1, 0x25, 0xbd, 0x8b, 0x5e, 0x6a, 0x7f, 0xca, 0x4a, 0xa6, 0x9e,
	0x55, 0xee, 0x49, 0x3f, 0xc4, 0x7a, 0x15, 0xfe, 0x5c, 0x4c, 0x27, 0xa0, 0xbb, 0xd6, 0xb5, 0x55,
	0xbb, 0xff, 0x06, 0x32, 0x69, 0x90, 0x7f, 0x29, 0xa6, 0x73, 0xb3, 0x17, 0x77, 0x1a, 0x5a, 0x6d,
	0x04, 0x3e, 0x6a, 0xf8, 0xeb, 0xb0, 0xb2, 0xee, 0xd4, 0x80, 0x79, 0xb1, 0x48, 0x1f, 0x0e, 0x96,
	0x54, 0x4a, 0x8b, 0x13, 0x55, 0x7a, 0xb6, 0x61, 0xbc, 0x51, 0xa4, 0x2e, 0x99, 0xda, 0xe1, 0x1e,
	0xdd, 0x76, 0xa3, 0x84, 0xbf, 0x15, 0xcb, 0x6f, 0x39, 0xfb, 0xd2, 0xd4, 0x15, 0x4f, 0x5f, 0x98,
	0xca, 0x9d, 0xbd, 0x30, 0x95, 0xfb, 0xe5, 0x85, 0xa9, 0xdc, 0xbb, 0xa7, 0x56, 0xad, 0xeb, 0x8b,
	0x06, 0xbd, 0xce, 0x2c, 0x7d, 0xff, 0x9a, 0x8d, 0xd6, 0xdb, 0xe9, 0xf7, 0xb5, 0xd5, 0x1d, 0xee,
	0xcb, 0xd9, 0xdb, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x9f, 0xf2, 0xd3, 0x79, 0x13, 0x00,
	0x00,
}

func (m *ErrDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErrDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErrDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Codes) > 0 {
		dAtA2 := make([]byte, len(m.Codes)*10)
		var j1 int
		for _, num := range m.Codes {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintErrcode(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintErrcode(dAtA []byte, offset int, v uint64) int {
	offset -= sovErrcode(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ErrDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Codes) > 0 {
		l = 0
		for _, e := range m.Codes {
			l += sovErrcode(uint64(e))
		}
		n += 1 + sovErrcode(uint64(l)) + l
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovErrcode(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozErrcode(x uint64) (n int) {
	return sovErrcode(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ErrDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowErrcode
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErrDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErrDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v ErrCode
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowErrcode
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= ErrCode(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Codes = append(m.Codes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowErrcode
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthErrcode
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthErrcode
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Codes) == 0 {
					m.Codes = make([]ErrCode, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v ErrCode
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowErrcode
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= ErrCode(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Codes = append(m.Codes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Codes", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipErrcode(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthErrcode
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipErrcode(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowErrcode
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowErrcode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowErrcode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthErrcode
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupErrcode
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthErrcode
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthErrcode        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowErrcode          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupErrcode = fmt.Errorf("proto: unexpected end of group")
)
