name: Android
on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'go/**'
      - 'go.*'
      - '**.go'
      - 'js/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'go/**'
      - 'go.*'
      - '**.go'
      - 'js/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            js/node_modules
            js/packages/*/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('js/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        env:
          CI: "true"
          SHAKEBUGS_API_ID: ${{ secrets.SHAKEBUGS_API_ID }}
          SHAKEBUGS_API_SECRET: ${{ secrets.SHAKEBUGS_API_SECRET }}
        run: |
          cd js
          if [ "$SHAKEBUGS_API_ID" != "" ] && [ "$SHAKEBUGS_API_SECRET" != "" ] ; then echo "SHAKE_API_ID=$SHAKEBUGS_API_ID\nSHAKE_API_SECRET=$SHAKEBUGS_API_SECRET" > .env ; fi
          make android.release

      - name: Upload the APK
        uses: actions/upload-artifact@v2
        with:
          path: js/packages/berty-app/android/universal.apk
          if-no-files-found: error
