name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
          working-directory: go
          args: --timeout=2m
          # only-new-issues: true
  protobuf:
    name: protobuf
    runs-on: ubuntu-latest
    container: bertytech/protoc:23
    steps:
      - uses: actions/checkout@v2
      - run: find . -name gen.sum ! -path './js/*' -delete
      - name: generating go/
        run: |
          cd go
          go mod vendor
          make generate_local
          cd ..
          git checkout go.mod go.sum
      - name: generating docs/
        run: |
          cd docs
          make generate_local
      #- name: generating js/
      #  run: |
      #    cd js
      #    make gen.clean
      #    make deps
      #    make gen.api
      #    make gen.codegen
      #    make generate_local
      - name: check diff
        run: |
          git status | cat
          diff -w | cat
          git diff-index -w --quiet HEAD --
