name: Integration
on:
  schedule:
    - cron: '0 * * * *'
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'go/**'
      - '!go/**.md'
      - 'go.*'
      - '**.go'
      - 'js/**'
      - '!js/packages/berty-i18n/locale/*/*.json'
      - '.github/workflows/integration.yml'
  pull_request:
    paths:
      - 'go/**'
      - '!go/**.md'
      - 'go.*'
      - '**.go'
      - 'js/**'
      - '!js/packages/berty-i18n/locale/*/*.json'
      - '.github/workflows/integration.yml'

# FIXME:
# * test on production periodically with env=production
# * test against a fresh docker-compose infra on each commit
# * store performance logs for comparison

jobs:
  unstable-tests:
    name: "env=production"
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      GOLANG: 1.15.x
    steps:
      - name: Generate run's URL
        id: url
        run: |
          echo "::set-output name=runUrl::https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Avoid triggering make generate
        run: touch go/gen.sum
      - name: Fetch dependencies
        run: go mod download
      - name: Compile the integration binary
        working-directory: go
        run: go install ./cmd/berty-integration
      - name: Run integration test suite
        run: |
          berty-integration \
            -integration.testbot=`cat ./config/config.gen.json | jq -r '.berty.contacts["testbot"].link'` \
            -integration.benchmark > benchmark_result.json
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{runner.os}}-integration-benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: false
          comment-on-alert: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          #alert-comment-cc-users: '@foobar'
          #auto-push: true
      - name: Discord notification
        if: github.event_name == 'schedule' && failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_DEV_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'Integration failed, see ${{ steps.url.outputs.runUrl }}'
