name: iOS
on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - 'go/**'
      - 'go.*'
      - '**.go'
      - 'js/**'
      - '.github/workflows/ios.yml'
  pull_request:
    paths:
      - 'go/**'
      - 'go.*'
      - '**.go'
      - 'js/**'
      - '.github/workflows/ios.yml'

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}  # see https://github.com/actions/checkout/issues/299

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: '12.0'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: |
            js/node_modules
            js/packages/*/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('js/**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-node-

      - name: Cache Ruby modules
        uses: actions/cache@v2
        with:
          path: js/vendor/bundle
          key: ${{ runner.OS }}-bundle-${{ hashFiles('js/Gemfile.lock') }}
          restore-keys: ${{ runner.OS }}-bundle-

      - name: Cache Gomobile .framework
        uses: actions/cache@v2
        with:
          path: js/packages/go-bridge/ios/Frameworks/Bertybridge.framework
          key: ios-gomobile-${{ hashFiles('go/**/*.go', 'go/**/*.m', 'go/**/*.h', 'go.sum') }}
          restore-keys: ios-gomobile-

      - name: Cache XCodeGen
        uses: actions/cache@v2
        with:
          path: js/vendor/xcodegen
          key: ios-xcodegen-${{ hashFiles('js/XCodeGen.version') }}
          restore-keys: ios-xcodegen-

      - name: Cache XCode project
        uses: actions/cache@v2
        with:
          path: js/packages/berty-app/ios/Berty.xcodeproj
          key: ios-xcodeproj-${{ hashFiles('js/packages/berty-app/ios/*.yaml') }}
          restore-keys: ios-xcodeproj-

      - name: Cache Pods and XCode workspace
        uses: actions/cache@v2
        with:
          path: |
            js/packages/berty-app/ios/Berty.xcworkspace
            js/packages/berty-app/ios/Pods
          key: ios-xcodeworkspace-${{ hashFiles('js/packages/berty-app/ios/Podfile.lock', 'js/**/yarn.lock') }}
          restore-keys: ios-xcodeworkspace-

      - name: Setup macOS keychain
        working-directory: tool/build/dummy-identity
        run: |
          security create-keychain -p "dummypass" dummy.keychain
          security default-keychain -s dummy.keychain
          security unlock-keychain -p "dummypass" dummy.keychain
          security set-keychain-settings dummy.keychain
          security import berty-dummy.p12 -t priv -f pkcs12 -P "dummypass" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "dummypass" dummy.keychain

      - name: Build .env
        run: cat tool/build/shakebugs-infos/env >> js/.env

      - name: Build the Archive
        working-directory: js
        run: |
          make ios.app_deps
          xcodebuild archive \
                -workspace packages/berty-app/ios/Berty.xcworkspace \
                -scheme "Berty Yolo" \
                -sdk iphoneos \
                -archivePath /tmp/Berty.xcarchive \
                CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO
          codesign -fs "Berty Dummy" /tmp/Berty.xcarchive/Products/Applications/Berty\ Yolo.app/Frameworks/Shake.framework
          codesign -fs "Berty Dummy" /tmp/Berty.xcarchive/Products/Applications/Berty\ Yolo.app
          mkdir Payload
          mv /tmp/Berty.xcarchive/Products/Applications/Berty\ Yolo.app Payload/
          zip -r ${{ github.workspace }}/Berty\ Yolo.dummy-signed-ipa Payload

      - name: Upload the Archive
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/Berty Yolo.dummy-signed-ipa
          name: berty-yolo-${{github.sha}}.dummy-signed-ipa
          if-no-files-found: error
